api:
  id: "20423041"
  client: 
    id: "702c28dbe10d47ab90a98ad3a9bf6402"
emergencyResponse:
  host: ersv3-71472g.5sc6y6-4.usa-e2.cloudhub.io
  port: "443"
  path: /api
  protocol: HTTPS
 
ehr:
  host: ehr-system-api-71472g.5sc6y6-1.usa-e2.cloudhub.io
  port: "443"
  path: /api
  protocol: HTTPS

mq:
  organizationId: "7f564899-8d0b-4816-b5a3-552642e8cc91"
  environmentId: "46ad7518-d4d3-421c-adf5-d7c6c0532a64"
  clientId: "f5748502d3f4425383ef57adfd027fa9"
    
# https://responder-api-dev-71472g.5sc6y6-1.usa-e2.cloudhub.io/