api:
  id: "0"
  client: 
    id: "just_something_fague"
    secret: "just_something_fague_secret"
emergencyResponse:
  host: localhost
  port: "9081"
  path: /api
  protocol: HTTP
 
ehr:
  host: localhost
  port: "9082"
  path: /api
  protocol: HTTP